# Generated by Django 3.2.25 on 2025-11-26 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa7f9ebd-1a83-4a97-bab1-ae0bd28b1b67'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
